title: 조윤식의 포폴사이트
name: 조윤식
email: appie6069@naver.com
description: >-
  Backend 개발자


baseurl: ""
url: "https://choyunsik.github.io/"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
facebook_id: <username>
instagram_id: <username>


# Youtube vid
youtube_vid: "oZnHOy9bXIc"


# Custom Color
primary: b72cf0 # 2c98f0 #b72cf0
primary_hover: ec5453 # 44A4F2 #2c98f0
color_1: b72cf0 # 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0
# 형식에 맞추어 항목 추가
#slider_0:
#- background_url: images/cover_bg_1.jpg
#  title: 안녕하세요
#  subtitle: >-
#    저는 백엔드 개발 분야에서 꾸준히 성장하며 <br> 새로운 기술을 습득하고 적용하는 것을 즐기고 있습니다.
#  position: absolute
#  transform: translate( -50%, -210% )
#  left: 120px
#  bottom: 80px



# slider type 1
# 형식에 맞추어 항목 추가
#slider_1:
#- background_url: images/cover_bg_2.jpg
#  title: Portfoilo Site
#  subtitle: >-
#    신기술에 대한 열정과 꾸준한 학습을 바탕으로 안정적이고 효율적인 서버 구축을 추구하는 백엔드 개발자입니다.
#  position: absolute
#  transform: translate( -50%, -150% )
#  left: 400px
#  bottom: 280px



# About
about_meta: About Me
about_header: >- 
  "백엔드 개발자의 성장 이야기"
about_introduce: >-
  "안녕하세요. 새로운 기술과 협업을 통해 발전하는 개발자 조윤식입니다."
about_content: >-
  안녕하세요, 저는 백엔드 개발자입니다.
  대학교에서 배운 전공지식을 바탕으로, 현재는 웹 애플리케이션 개발에 익숙하며, 사용자가 만족할 수 있는 서비스를 만드는 것에 큰 보람을 느끼고 있습니다.

  하지만 개발자로서의 성장은 멈출 수 없는 과정이라고 생각합니다. 저는 항상 새로운 기술과 도구를 배우는 것에 열려 있으며, 이를 활용해 더 나은 소프트웨어를 개발하기 위해 노력합니다. 특정 기술에 국한되지 않고, 다양한 환경과 패러다임을 경험하며 확장 가능한 시스템을 구축하는 데 관심이 많습니다.

  또한, 개발에서 가장 중요한 요소 중 하나는 협업이라고 생각합니다. 소프트웨어 개발은 혼자가 아니라 팀과 함께 이루어지는 과정이며, 저는 협업을 통해 더 나은 결과물을 만들어가는 것을 좋아합니다. 다양한 아이디어를 주고받으며 발전하는 팀워크를 즐기고, 함께 성장하는 경험을 소중하게 여깁니다.

  앞으로도 저는 지속적으로 배우고 도전하며, 더 나은 개발자가 되기 위해 노력하겠습니다.

about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: Java
- icon: icon-leaf
  name: Spring
- icon: icon-monitor
  name: Back-end
- icon: icon-study
  name: 정보관리기술사


#about_box_content: >-
#  저는 잘 살기 위해서는 어떤 마음가짐으로 살아가야 할지를 진지하게 고민해보았습니다. <br>
#  다양한 분야에서 성공한 사람들을 보면 그들은 각자의 분야에서 성공하기 위한 비결을 갖고 있었습니다. <br>
#  그들이 성공한 것은 단지 열정과 노력뿐만 아니라 <br>
#  자신을 내세우며 자신의 분야에서 필요한 능력과 태도를 갖추었기 때문입니다.<br>
#  저도 개발자로서 성공하기 위해서는 "개발자다움"이란 것을 갖추어야 한다는 생각이 들었습니다. <br>
#  개발자다움은 자신의 일에 대한 열정과 책임감, 그리고 끊임없는 학습과 발전으로 이루어진다고 생각합니다. <br>
#  이러한 개발자다움의 정신을 바탕으로, <br>
#  저는 현재 개발한 것에 만족하지 않고 더 나은 프로그램을 개발하기 위해 노력하고 있습니다.<br>
#  더불어, 맡은 프로젝트가 더욱 발전할 수 있도록 최선을 다하고 있습니다. <br>
#  프로젝트를 완성하는 것에 그치지 않고, <br>
#  더 나은 프로그램을 만들기 위해 항상 새로운 아이디어를 모색하고 기술적인 도전에 끊임없이 도전합니다.<br>
#  나의 목표는 끊임없이 발전하며, 다양한 경험과 능력을 통해 성장하는 것입니다.<br>
#  저는 더 나은 개발자가 되기 위해 자신의 역량을 끊임없이 향상시키고,<br>
#  이를 통해 사람들에게 더 많은 가치를 제공할 수 있도록 노력할 것입니다.<br>
#
#about_box_content_color : rgb(255,255,255)
#
#about_box_button:
#  link: https://ysiksik.github.io/
#  name: 개발자 답게 살겠습니다


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content:
  저는 백엔드 개발자로서 다양한 기술과 경험을 쌓아가고 있습니다. 주요 프로그래밍 언어를 활용하여 확장 가능하고 유지보수가 용이한 서버 애플리케이션을 개발하며, RESTful API 및 다양한 아키텍처 패턴을 적용하여 안정적인 서비스를 구축하는 데 집중하고 있습니다.

  API 개발 과정에서는 문서화 도구를 활용해 명세서를 작성하고, 인증 및 보안 기능을 구현하여 안정적인 서비스를 제공합니다. 또한, 데이터베이스 설계 및 최적화를 중요하게 여기며, ORM 기술을 활용하여 효율적인 데이터 처리 로직을 구현할 수 있습니다.

  최근에는 **MSA(Microservices Architecture)**에 관심을 가지고 학습하고 있습니다. 서비스 간 분리 및 확장성을 고려한 구조에 대해 이해하고 있으며, 더 나은 시스템을 설계하기 위해 지속적으로 공부하고 있습니다.

  뿐만 아니라, 협업을 위한 Git 버전 관리 및 프로젝트 관리 도구(JIRA, Confluence 등)를 활용하여 효과적인 협업 환경을 조성하는 데 익숙합니다. 보안 및 아키텍처 설계 역량을 강화하기 위해 지속적인 학습을 진행하고 있으며, 기술 블로그와 개발 커뮤니티를 통해 지식을 공유하고 성장하고 있습니다.

tech_list: # 형식에 맞추어 항목 추가
- name: Java
  color: color-1
  animation: fadeInLeft
  percent: 80
  mark: 80
  content:
     객체지향 프로그래밍(OOP) 원칙과 디자인 패턴을 적용하여 유지보수성과 확장성이 높은 코드를 작성하는 데 집중합니다. 멀티스레딩, 컬렉션 프레임워크, 스트림 API 등의 기능을 활용하여 효율적인 애플리케이션을 개발한 경험이 있습니다.

- name: Spring Framework
  color: color-2
  animation: fadeInRight
  percent: 80
  mark: 80
  content:
    Spring Framework를 활용하여 REST API 및 웹 애플리케이션을 개발하고 있습니다. API 문서화를 위해 Swagger를 사용하며, Spring Security를 적용하여 보안 기능을 강화합니다. 또한, JSP, Thymeleaf 등의 템플릿 엔진을 활용하여 동적인 웹 페이지를 개발할 수 있습니다.

- name: Spring Batch
  color: color-3
  animation: fadeInRight
  percent: 70
  mark: 70
  content:
    대량의 데이터를 효율적으로 처리하기 위해 Spring Batch를 활용하여 배치 작업을 설계하고 최적화할 수 있습니다. 정산, 로그 분석, 데이터 마이그레이션 등 반복적인 작업을 자동화하고, 성능 최적화를 고려한 배치 프로세스를 구현한 경험이 있습니다.

- name: MSA
  color: color-6
  animation: fadeInRight
  percent: 70
  mark: 70
  content:
    Microservices Architecture(MSA)에 대한 이해를 바탕으로 서비스 간 분리 및 독립적인 배포 환경을 고려한 설계를 진행합니다. 서비스 간 통신(Feign Client, gRPC), 분산 데이터 관리 전략 등을 연구하며, 대규모 시스템 확장성을 높이는 방법을 학습하고 있습니다.

- name: Thymeleaf
  color: color-1
  animation: fadeInRight
  percent: 50
  mark: 50
  content:
    Spring 기반 웹 애플리케이션에서 Thymeleaf 템플릿 엔진을 활용하여 동적인 웹 페이지를 개발합니다. HTML과 자연스럽게 통합되며, 서버 사이드 렌더링(SSR) 방식으로 UI를 구성하여 유지보수성을 높일 수 있습니다.

- name: CI/CD & 협업 도구
  color: color-4
  animation: fadeInRight
  percent: 60
  mark: 60
  content:
    CI/CD 환경을 구축하여 개발 및 배포 프로세스를 자동화할 수 있으며, Jenkins 및 GitHub Actions를 활용한 빌드 및 배포 자동화 경험이 있습니다. 또한, Git을 활용한 협업과 버전 관리에 익숙하며, JIRA 및 Confluence 등의 프로젝트 관리 도구를 통해 체계적인 협업을 진행할 수 있습니다.

# 마무리
tech_desc:
  Kubernetes와 Docker를 활용한 컨테이너 환경 구성과 운영에 대한 이해를 넓히고 있으며, 이를 실무에 효과적으로 적용하기 위해 지속적으로 학습하고 있습니다. 또한, IT 시스템의 설계 및 운영 역량을 강화하기 위해 정보관리기술사 자격증 취득을 목표로 하고 있습니다.




# Project
project_meta: My Work
project_header: PROJECT
#project_introduce:
#  간단히 내가 수행해온 project 소개

#project_my_name: 프로젝트

project_my: # 형식에 맞추어 항목 추가
#- background_url: images/personal_project1.PNG
#  animation: fadeInLeft
#  name: 딥러닝 불량품 검출(2021.04)
#  description: 실패한 공모전을 대학원 기말 프로젝트를 통해 몰랐던부분을 배우고 해결하였습니다. 공장에서 만들어내는 부품의 데이터를 통해 불량품을 검출하는 프로젝트입니다.
#  detail_url: #
#  readmore_url: #

- background_url: images/project3.png
  animation: fadeInLeft
  name: 결제 시스템 (PG) (총 15개 프로젝트로 구성)
  description: 전자 상거래, 모바일 앱, POS(Point of Sale) 환경에서 다양한 결제 수단(신용카드, 계좌이체 등)을 안전하고 신속하게 처리하는 결제 시스템을 구축했습니다. 결제 API 개발, 원천사 연동, 인증 시스템 구현 등을 통해 안정적인 트랜잭션 환경을 제공합니다.
  detail_url: https://ysiksik.github.io/payment-system/
#  readmore_url: #

- background_url: images/project2.png
  animation: fadeInLeft
  name: 쿠폰 서비스 (총 5개 프로젝트로 구성)
  description: 사용자가 모바일을 통해 간편하게 쿠폰을 발급·사용할 수 있도록 하는 소액 결제 기반의 쿠폰 서비스입니다. 할인 적용, 프로모션 관리, 쿠폰 복원 및 취소 기능을 포함하며, 다양한 결제 시스템과 연동하여 원활한 사용자 경험을 제공합니다.
  detail_url: https://ysiksik.github.io/coupon-service/
#  readmore_url: #

- background_url: images/project1.png
  animation: fadeInLeft
  name: 비트코인 거래소
  description: 비트코인 및 암호화폐 거래를 위한 웹 기반 거래소를 개발했습니다. 사용자는 이 플랫폼을 통해 안전하게 암호화폐를 구매·판매할 수 있으며, 실시간 거래 기능, 지갑 연동, 보안 강화된 결제 프로세스를 통해 원활한 거래 환경을 제공합니다.
  detail_url: https://ysiksik.github.io/coin-exchange/
#  readmore_url: #

#project_team_name: 팀프로젝트
#
#project_team: # 형식에 맞추어 항목 추가
#- background_url: images/team_project3.PNG
#  animation: fadeInRight
#  name: Anti-Drone_Robot(2020.05)
#  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#  detail_url: #
#  readmore_url: #
#
#- background_url: images/team_project3.PNG
#  animation: fadeInRight
#  name: Anti-Drone_Robot(2020.05)
#  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#  detail_url: #
#  readmore_url: #
#
#- background_url: images/team_project3.PNG
#  animation: fadeInRight
#  name: Anti-Drone_Robot(2020.05)
#  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#  detail_url: #
#  readmore_url: #
#
#- background_url: images/team_project3.PNG
#  animation: fadeInRight
#  name: Anti-Drone_Robot(2020.05)
#  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#  detail_url: #
#  readmore_url: #
#
#project_business_name: Business
#project_business: # 형식에 맞추어 항목 추가
#- background_url: images/my_business.PNG
#  animation: fadeInTop
#  name: 인프런강의(2021~)
#  description: >-
#    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만)
#    또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다.
#    많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까.
#    공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다.
#  detail_url: #
#  readmore_url: #
#
## 더보기 내용
#project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)
#project_load_more_url: https://github.com/khw11044




# Experience
exp_meta: What have I achieved?
exp_header: 이런 경험을 통해 성장해왔습니다.
exp_content: 이러한 경험들은 개발자로서의 역량을 키우는 데 큰 도움이 되었으며, 실무에서 효과적으로 적용할 수 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 문제 해결 능력
  color: color-1
  icon: icon-bulb
  content: 🛠️ 복잡한 버그를 분석하고 디버깅하는 과정에서 논리적 사고와 효율적인 해결 방법을 익혔습니다. 코드 최적화 및 성능 개선을 통해 안정적인 서비스를 제공하는 데 집중하고 있습니다.
- name: 지속적인 학습과 기술 적용
  color: color-2
  icon: icon-home
  content: 📚 새로운 기술 트렌드를 따라가며, 이를 실무에 적용하는 데 적극적입니다. 기술 서적 및 온라인 강의를 통해 학습한 내용을 직접 프로젝트에 반영하여 성장하고 있습니다.
- name: 프로젝트 관리 및 협업
  color: color-3
  icon: icon-phone3
  content: 📌 다양한 프로젝트를 기획, 설계, 개발하면서 일정 관리 및 협업의 중요성을 경험했습니다. 역할 분배와 업무 조정을 통해 팀원들과 효과적으로 협업하며 프로젝트를 성공적으로 완수한 경험이 있습니다.
- name: 코드 품질 향상
  color: color-4
  icon: icon-bulb
  content: 📝 가독성, 유지보수성, 재사용성을 고려한 코드 작성에 집중하며, 코드 리뷰를 통해 팀 내 코드 품질을 개선하는 데 기여했습니다. 클린 코드 원칙을 실천하며, 지속적인 리팩토링을 통해 최적화된 코드를 유지하고 있습니다.
- name: 리더십 경험
  color: color-1
  icon: icon-home
  content: 🎯 프로젝트 진행 시 팀 내에서 리더 역할을 수행한 경험이 있습니다. 팀원들과 원활한 소통을 유지하며 일정 조율 및 의사결정을 주도하였고, 목표 달성을 위해 체계적으로 프로젝트를 관리하였습니다.
- name: 팀워크 & 커뮤니케이션 능력
  color: color-2
  icon: icon-phone3
  content: 🤝 원활한 협업을 위해 팀원들과 적극적으로 소통하며, 비개발자(기획자, 디자이너, 클라이언트)와의 커뮤니케이션을 통해 요구사항을 조율한 경험이 있습니다. 문제 발생 시 의견을 조율하고 갈등을 중재하는 역할도 수행하였습니다.


#exp_counters_bg_img: images/about.jpg
#exp_counters:
#- name: Online Class Sales
#  count: 344
#  speed: 10000
#- name: Project
#  count: 6
#  speed: 5000
#- name: Business
#  count: 100
#  speed: 20000



# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 트레드링스
  date: 2023.08 ~ 재직 중
  content: 웹 스크래핑을 활용한 데이터 수집 시스템을 개발·운영하며, 광고 플랫폼을 구축하여 타겟팅 광고 기능을 최적화했습니다. 또한, 알림 센터 시스템을 통해 여러 프로젝트의 알림을 통합 관리하고, 알림 배치 작업을 통해 변경 사항을 자동으로 전송하는 기능을 개발했습니다. 더불어, PAYPAL 및 STRIPE 구독 결제를 연동하여 정기 결제 기능을 안정적으로 운영하며, 데이터 기반 서비스를 통해 고객 비즈니스 성과 향상에 기여하고 있습니다.
  color: color-5
  icon: icon-pen2
  animation: fadeInLeft
#  url: https://ysiksik.github.io/payment-system/
- name: 립페이
  date: 2021.04 ~ 2023.07
  content: 결제 서비스(PG) 시스템 개발을 담당하며, 가맹점·대리점·원천사 연동 API를 구축하여 안정적인 결제 환경을 제공했습니다. 인증 결제, 배치 처리, 관리자 페이지 개발을 수행하며, 대규모 결제 트랜잭션 처리 및 결제 프로세스 최적화를 경험했습니다.
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
  url: https://ysiksik.github.io/payment-system/
- name: 크레디프
  date: 2019.08 ~ 2021.04
  content: 쿠폰 서비스 API 및 관리 시스템을 개발하며, 쿠폰 발급·사용·취소 프로세스를 구축하고, 배치 작업을 통해 데이터 처리 자동화를 수행했습니다. 서비스 안정성과 성능을 개선하며, 쿠폰 시스템 운영을 통해 데이터 활용 및 최적화 역량을 쌓았습니다
  color: color-2
  icon: icon-pen2
  animation: fadeInRight
  url: https://ysiksik.github.io/coupon-service/
- name: 코엔코코리아
  date: 2018.03 ~ 2019.08
  content: 비트코인 거래소 및 암호화폐 지갑 서버 구축을 담당하며, FSDC 클라우드 기반의 서버 인프라를 구축하고 운영했습니다. 또한, ISMS 인증을 위한 보안 설계 및 관리 경험을 통해 금융 시스템의 안정성과 보안 강화를 위한 아키텍처 설계를 익혔습니다.
  color: color-3
  icon: icon-pen2
  animation: fadeInRight
  url: https://ysiksik.github.io/coin-exchange/
- name: 솔비텍
  date: 2017.01 ~ 2018.03
  content: 리포팅 툴 유지보수 및 기술 지원을 담당하며, 시스템 성능 개선 및 최적화를 수행했습니다. 기존 시스템의 문제점을 분석하고 최적화 작업을 진행하여, 서비스 안정성을 높이고 유지보수성을 향상시켰습니다.
  color: color-4
  icon: icon-pen2
  animation: fadeInRight




# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: 국가평생교육진흥원
  subtitle: 국가평생교육진흥원 멀티미디어학과 학사 졸업
  date: 2017.05 ~ 2018.03
  content: >-
    정보처리기사 취득과 함께, 학사 학위를 목표로 학습하며 IT 분야로의 진출을 준비했습니다. 이 과정에서 자기주도적인 학습 태도를 키웠으며, 문제 해결 능력과 지속적인 성장의 중요성을 배웠습니다. 현재는 실무에서 쌓은 경험을 바탕으로 새로운 기술을 적극적으로 탐구하며 경력을 확장해 나가고 있습니다.
- title: 동원 대학교
  subtitle: 동원 대학교 스마트 IT 콘텐츠학과 전문 학사 졸업
  date: 2013.03 ~ 2017.02
  content: >-
    IT 분야에 대한 흥미와 도전 정신을 바탕으로 학습을 시작하였으며, 학업 과정에서 다양한 프로젝트에 참여하며 실무 경험을 쌓았습니다. 특히, 미숙했던 분야에 대한 적극적인 학습을 통해 새로운 기술을 습득하는 능력을 기르고, 문제 해결과 협업의 중요성을 체득했습니다. 


# self-improvement
blog_meta: self-improvement
blog_header: BLOG
#blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: 개발 블로그
  subtitle: 개발 블로그 운영
  content: 백엔드 개발 분야에서 꾸준히 성장하며, 새로운 기술을 습득하고 실무에 적용하는 것을 즐깁니다. 이 블로그를 통해 배운 내용을 정리하고 개발 경험을 공유하며, 다른 개발자들과 함께 성장하는 공간을 만들어가고 있습니다.
  thumbnail_url: images/cover_bg_2.jpg
  link: https://ysiksik.github.io/



# Contact
#contact_meta: Get in Touch
#contact_header: Contact
#contact_list:
#- title: appie6069@naver.com
#  icon: icon-globe-outline
#- title: 서울특별시 노원구
#  icon: icon-map
#- title: +82 10 xxxx xxxx
#  icon: icon-phone
#- title: 내 Github
#  icon: icon-layers2
#  url: https://github.com/khw11044



optional_front_matter:
  remove_originals:    true
