title: 조윤식의 포폴사이트
name: 조윤식
email: appie6069@naver.com
description: >-
  Java/Spring 기반 백엔드 엔지니어


baseurl: ""
url: "https://choyunsik.github.io/"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
facebook_id: <username>
instagram_id: <username>


# Youtube vid
youtube_vid: "oZnHOy9bXIc"


# Custom Color
primary: b72cf0 # 2c98f0 #b72cf0
primary_hover: ec5453 # 44A4F2 #2c98f0
color_1: b72cf0 # 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0
# 형식에 맞추어 항목 추가
slider_0:
- background_url: images/cover_bg_1.jpg
  title: 안녕하세요
  subtitle: >-
    저는 백엔드 개발 분야에서 꾸준히 성장하며 <br> 새로운 기술을 습득하고 적용하는 것을 즐기고 있습니다.
  position: absolute
  transform: translate( -50%, -202% )
  left: 120px
#  bottom: 80px



# slider type 1
# 형식에 맞추어 항목 추가
slider_1:
- background_url: images/cover_bg_2.jpg
  title: Portfoilo Site
  subtitle: >- 
    신기술에 대한 열정과 꾸준한 학습을 바탕으로 안정적이고 효율적인 서버 구축을 추구하는 백엔드 개발자입니다.
  position: absolute
  transform: translate( -50%, -150% )
  left: 400px
#  bottom: 280px



# About
about_meta: About Me
about_header: >- 
  "Java와 Spring을 활용한 백엔드 개발자의 성장 이야기"
about_introduce: >-
  "안녕하세요. 새로운 기술과 협업을 통해 발전하는 개발자 조윤식입니다."
about_content: >-
  안녕하세요, 저는 Java와 Spring을 활용한 백엔드 개발자입니다. 대학교에서 전공으로 배운 내용을 기반으로, 현재는 웹 어플리케이션 개발에 매우 익숙합니다. 지금까지의 경력을 통해, 제가 만든 프로그램들이 사용자들에게 좋은 경험을 제공하게 된다는 것을 목격했습니다.

  하지만, 개발자로서 성장하는 것은 멈출 수 없는 과정입니다. 저는 항상 새로운 기술과 프레임워크를 배우는 것에 열려있으며, 이를 이용하여 더욱 발전한 소프트웨어를 만들기 위해 노력합니다. 지금까지는 Java와 Spring을 중심으로 개발을 진행해왔지만, 새로운 기술과 도구를 배우고 적용하는 것에 큰 흥미를 느끼고 있습니다.

  또한, 제가 가장 중요하게 생각하는 것 중 하나는 협업입니다. 개발은 혼자하는 것이 아닌, 팀으로 진행되는 작업입니다. 저는 팀에서 협업하는 것을 좋아합니다. 서로가 서로의 아이디어를 나누며 더욱 발전하는 팀워크를 즐기는 편입니다. 또한, 다른 개발자들과 함께 일하면서 배울 것이 많고, 새로운 아이디어와 시각을 얻을 수 있다는 것을 깨달았습니다.

  이렇게, 저는 계속해서 새로운 기술과 협업을 통해 발전하는 개발자가 되고자 합니다.

about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: Java
- icon: icon-leaf
  name: Spring
- icon: icon-monitor
  name: Back-end
- icon: icon-study
  name: 정보관리기술사


about_box_content: >-
  “천재는 즐기는 사람을 이길수 없고 <br>
  즐기는 사람은 노력하는 사람을 이길 수 없다.” 라는 말이있습니다. <br><br>
  하지만 그 누구도 수십년을 꾸준히 해온 </br>
  <b>'장인'</b>은 이길수 없습니다

about_box_content_color : rgb(255,255,255)

about_box_button:
  link: https://github.com/khw11044
  name: 이 분야의 '장인'이 되겠습니다.


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content:
  개발의 처음 시작은 C++,java로 시작하였습니다. 
  이후에 딥러닝에 관심을 갖으면서 Python을 바탕으로 패스트캠퍼스, 인프런, 코드라이언등을 통해 공부하고 현재는 고려대 인공지능 대학원에서 컴퓨터비전분야를 공부하고 있습니다. 
  간단한 웹서비스를 개발할 수 있으며, 서버에서는 REST API를 통해 Web Server를 구현 할 수 있습니다. 
  Firebase, Flask를 할수 있습니다. 
  하지만 워낙 따라하기 위주로 공부하다 보니 이론적으로 약하고 그 깊이가 얕습니다. 
  현재는 저는 인공지능 대학원생으로 다른 공부는 멈추고 저의 연구분야에 집중하여 공부하고 있습니다.
  GitHub을 통해 소스 코드 및 프로젝트를 관리하고 협업하고 있습니다. 프로젝트 관리툴로는 Slack, Trello, Google Drive, Github, Notion 등을 경험하였습니다. 
  <b>CCNA(Cisco Certified Network Associate Routing and Switching)</b> 자격증을 따면서 네트워크에 대해 간단히 알고있습니다. 
  <b>Internet of Things Knowledge Certification<b>을 따면서 사물인터넷에 대해 간단히 알고있습니다.

tech_list: # 형식에 맞추어 항목 추가
- name: Python
  color: color-1
  animation: fadeInLeft
  percent: 60
  mark: 60
  content:
    파이썬 기초, 데이터 분석과 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 파이썬으로 공부하였습니다.

- name: 딥러닝
  color: color-2
  animation: fadeInRight
  percent: 10
  mark: 20
  content:
    공부하면 공부할수록 이 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다. 통계 이론부터 다시 배우겠다는 마음으로 공부하고 있습니다.

- name: AWS
  color: color-3
  animation: fadeInLeft
  percent: 20
  mark: 20
  content:
    AWS를 서버로 활용하며, IOT 프로젝트를 해보았습니다. 현재는 도커에 대해 학습하고 있습니다.

- name: Github
  color: color-4
  animation: fadeInRight
  percent: 30
  mark: 30
  content:
    대부분의 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.

- name: HTML
  color: color-6
  animation: fadeInRight
  percent: 50
  mark: 50
  content:
    HTML은 조금 할줄 압니다.

# 마무리
tech_desc:
  앞으로 연구한것을 서비스화하기 위해서 javascript, Node JS, 리엑트, 스피링, 헤로쿠, python anywhere 및 아마존 AWS, docker등을 계속해서 조금씩 공부할 생각입니다.




# Project
project_meta: My Work
project_header: PROJECT
project_introduce:
  간단히 내가 수행해온 project 소개

project_my_name: 개인프로젝트

project_my: # 형식에 맞추어 항목 추가
- background_url: images/personal_project1.PNG
  animation: fadeInLeft
  name: 딥러닝 불량품 검출(2021.04)
  description: 실패한 공모전을 대학원 기말 프로젝트를 통해 몰랐던부분을 배우고 해결하였습니다. 공장에서 만들어내는 부품의 데이터를 통해 불량품을 검출하는 프로젝트입니다.
  detail_url: #
  readmore_url: #

- background_url: images/blog-1.PNG
  animation: fadeInLeft
  name: GitBlog 만들기
  description: GitPages를 이용해서 블로그를 만들어보았습니다.
  detail_url: #
  readmore_url: #

- background_url: images/blog-1.PNG
  animation: fadeInLeft
  name: GitBlog 만들기
  description: GitPages를 이용해서 블로그를 만들어보았습니다.
  detail_url: #
  readmore_url: #

- background_url: images/blog-1.PNG
  animation: fadeInLeft
  name: GitBlog 만들기
  description: GitPages를 이용해서 블로그를 만들어보았습니다.
  detail_url: #
  readmore_url: #

project_team_name: 팀프로젝트

project_team: # 형식에 맞추어 항목 추가
- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: Anti-Drone_Robot(2020.05)
  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
  detail_url: #
  readmore_url: #

- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: Anti-Drone_Robot(2020.05)
  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
  detail_url: #
  readmore_url: #

- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: Anti-Drone_Robot(2020.05)
  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
  detail_url: #
  readmore_url: #

- background_url: images/team_project3.PNG
  animation: fadeInRight
  name: Anti-Drone_Robot(2020.05)
  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
  detail_url: #
  readmore_url: #

project_business_name: Business
project_business: # 형식에 맞추어 항목 추가
- background_url: images/my_business.PNG
  animation: fadeInTop
  name: 인프런강의(2021~)
  description: >-
    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
    또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
    많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
    공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다.
  detail_url: #
  readmore_url: #

# 더보기 내용
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)
project_load_more_url: https://github.com/khw11044




# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 매니지먼트
  color: color-1
  icon: icon-bulb
  content: 6개의 프로젝트 모두 팀장을 맡아 각 팀원들의 능력을 파악하고 업무를 배정하고 관리하였습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
- name: 프로젝트2
  color: color-6
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
exp_counters_bg_img: images/about.jpg
exp_counters:
- name: Online Class Sales
  count: 344
  speed: 10000
- name: Project
  count: 6
  speed: 5000
- name: Business
  count: 100
  speed: 20000



# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 과기전통부 산학과제
  date: 2020.06~2020.11
  content: PlenOPtic Video에서 객체 tracking 연구  <br> 중대형 공간용 초고해상도 비정형 플렌옵틱 동영상 저작/재생 플랫폼 기술 개발
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
  url: https://github.com/khw11044/PlenOpticVot_Siamfc_2020 #
- name: Voice Caddie 산학과제
  date: 2021.05~2021.10
  content: 현재 골프치는 사람의 Pose와 Multi-view를 연구하고 있습니다.
  color: color-2
  icon: icon-pen2
  animation: fadeInRight
  url: #
- name: Voice Caddie 산학과제
  date: 2021.05~2021.10
  content: 현재 골프치는 사람의 Pose와 Multi-view를 연구하고 있습니다.
  color: color-2
  icon: icon-pen2
  animation: fadeInRight
  url: #


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: XX UNIVERSITY ARTIFICIAL INTELLIGENCE MASTER'S DEGREE
  subtitle: XX대 인공지능학과 대학원 석사과정
  date: 20xx.01 - 현재
  content: >- 
    나에대한 간단한 설명글
- title: XX UNIVERSITY
  subtitle: xx대학교 xx과 졸업
  date: 20xx.03 - 20xx.02
  content: >-
    나에대한 간단한 설명글
- title: XX HIGH SCHOOL
  subtitle: xx고등학교
  date: 20xx.03 - 20xx.02
  content: >-
    나에대한 간단한 설명글 


# self-improvement
blog_meta: self-improvement
blog_header: BLOG and YOUTUBE
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: 개발 블로그
  subtitle: 개발 블로그 운영
  date: 2021.01
  content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해오고 있습니다.
  thumbnail_url: images/blog-1.PNG
  link: https://khw11044.github.io
- title: 따라쟁이의 유튜브
  subtitle: 개발,논문 유튜브 채널 운영
  date: 2018.04
  content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
  thumbnail_url: images/blog-2.PNG
  link: #
- title: 네이버블로그
  subtitle: 이전 블로그
  date: 2018.03
  content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
  thumbnail_url: images/blog-3.PNG
  link: #
- title: 네이버블로그
  subtitle: 이전 블로그
  date: 2018.03
  content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
  thumbnail_url: images/blog-3.PNG
  link: #


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: khw11044@gmail.com
  icon: icon-globe-outline
- title: 서울특별시 동작구
  icon: icon-map
- title: +82 10 xxxx xxxx
  icon: icon-phone
- title: 내 Github
  icon: icon-layers2
  url: https://github.com/khw11044



optional_front_matter:
  remove_originals:    true
